name = "CUDSS"
uuid = "45b445bb-4962-46a0-9369-b4df9d0f772e"
authors = ["Alexis Montoison <alexis.montoison@polymtl.ca>"]
version = "0.2.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS_jll = "4889d778-9329-5762-9fec-0578a5d30366"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CEnum = "0.4, 0.5"
CUDA = "5.3.0"
CUDSS_jll = "0.2.1"
julia = "1.6"
LinearAlgebra = "1.6"
SparseArrays = "1.6"
Random = "1.6"
Test = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
