[deps]
CUDA_SDK_jll = "6cbf2f2e-7e60-5632-ac76-dca2274e0be0"
CUDSS_jll = "4889d778-9329-5762-9fec-0578a5d30366"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
CUDA_SDK_jll = "13.0.1"
CUDSS_jll = "0.7.0"
julia = "1.10"
